name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    #  Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: List packaged files
      run: ls -la target/

    - name: Upload JAR to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "target/demo-0.0.1-SNAPSHOT.jar"
        target: "/opt/app/"
        rm: true

    - name: Restart Application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo ">>> 重启应用服务 <<<"
          sudo systemctl restart demo.service
          echo ">>> 等待应用启动 ... <<<"
          sleep 10
          echo ">>> 检查服务状态 <<<"
          sudo systemctl status demo.service --no-pager